version: '3.8'

services:
  sso-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sso/storage:/root/apps/grpc-sso
    ports:
      - "44044:44044"
    environment:
      CONFIG_PATH: "/app/sso/config/prod.yaml"
      ENV_FILE_PATH: "/app/config.env"

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined # This is optional and might be a security risk
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./sso/storage:/config  # Assuming you want to access the same volume
    ports:
      - 3000:3000
    restart: unless-stopped

networks:
  default:
    driver: bridge
